export interface ShopProduct {
  id: string;
  title: string;
  description: string;
  category: string;
  categoryLabel: string;
  priceRange: string;
  rating: number;
  reviewCount: string;
  badge?: string;
  emoji: string;
  features: string[];
  amazonUrl: string;
  asin: string;
}

const TAG = 'convertnow-20';
const BASE = 'https://www.amazon.ca';

export const SHOP_PRODUCTS: ShopProduct[] = [
  {
    id: 'kitchen-scale-001',
    title: 'Digital Kitchen Scale',
    description: 'Precise measurements in grams, oz, lbs and kg. Perfect for baking and cooking recipes.',
    category: 'cooking',
    categoryLabel: '🍳 Kitchen & Cooking',
    priceRange: '$15 – $35',
    rating: 4.7,
    reviewCount: '12,000+',
    badge: 'Best Seller',
    emoji: '⚖️',
    features: ['Measures in g, oz, lbs, kg, ml', 'Tare function for bowls', 'LCD display', 'Batteries included'],
    amazonUrl: `${BASE}/s?k=digital+kitchen+scale&tag=${TAG}`,
    asin: 'kitchen-scale',
  },
  {
    id: 'measuring-cups-001',
    title: 'Stainless Steel Measuring Cups & Spoons Set',
    description: 'Professional grade set with both metric and imperial markings. Essential for any kitchen.',
    category: 'cooking',
    categoryLabel: '🍳 Kitchen & Cooking',
    priceRange: '$18 – $40',
    rating: 4.8,
    reviewCount: '8,500+',
    badge: 'Top Rated',
    emoji: '🥄',
    features: ['Metric and imperial markings', 'Dishwasher safe', 'Set of 10 pieces', 'Stackable design'],
    amazonUrl: `${BASE}/s?k=stainless+steel+measuring+cups+spoons+set&tag=${TAG}`,
    asin: 'measuring-cups',
  },
  {
    id: 'meat-thermometer-001',
    title: 'Instant Read Meat Thermometer',
    description: 'Get perfectly cooked meat every time. Reads in both Celsius and Fahrenheit in 2 seconds.',
    category: 'cooking',
    categoryLabel: '🍳 Kitchen & Cooking',
    priceRange: '$15 – $45',
    rating: 4.8,
    reviewCount: '25,000+',
    badge: 'Most Popular',
    emoji: '🌡️',
    features: ['Reads in °C and °F', '2-second reading', 'Foldable probe', 'Waterproof'],
    amazonUrl: `${BASE}/s?k=instant+read+meat+thermometer&tag=${TAG}`,
    asin: 'meat-thermometer',
  },
  {
    id: 'glass-measuring-cups-001',
    title: 'Pyrex Glass Measuring Cup Set',
    description: 'Classic glass measuring cups with both metric (mL) and imperial (cups) markings.',
    category: 'cooking',
    categoryLabel: '🍳 Kitchen & Cooking',
    priceRange: '$20 – $50',
    rating: 4.9,
    reviewCount: '15,000+',
    emoji: '🫙',
    features: ['Microwave safe', 'Dishwasher safe', 'mL and cup markings', 'Set of 3'],
    amazonUrl: `${BASE}/s?k=pyrex+glass+measuring+cup+set&tag=${TAG}`,
    asin: 'glass-measuring-cups',
  },
  {
    id: 'bathroom-scale-001',
    title: 'Digital Bathroom Scale with BMI',
    description: 'Track your weight in kg or lbs. Shows BMI, body fat percentage and more.',
    category: 'fitness',
    categoryLabel: '💪 Fitness & Health',
    priceRange: '$25 – $65',
    rating: 4.6,
    reviewCount: '9,200+',
    badge: 'Popular',
    emoji: '🏋️',
    features: ['Displays kg and lbs', 'BMI calculation', 'App connected', 'Tempered glass'],
    amazonUrl: `${BASE}/s?k=digital+bathroom+scale+BMI&tag=${TAG}`,
    asin: 'bathroom-scale',
  },
  {
    id: 'fitness-tracker-001',
    title: 'Fitness Tracker Smart Watch',
    description: 'Track steps, distance in km or miles, heart rate, and calories burned.',
    category: 'fitness',
    categoryLabel: '💪 Fitness & Health',
    priceRange: '$35 – $120',
    rating: 4.5,
    reviewCount: '18,000+',
    badge: "Editor's Choice",
    emoji: '⌚',
    features: ['km and miles tracking', 'Heart rate monitor', 'Sleep tracking', 'Waterproof IP68'],
    amazonUrl: `${BASE}/s?k=fitness+tracker+smart+watch&tag=${TAG}`,
    asin: 'fitness-tracker',
  },
  {
    id: 'luggage-scale-001',
    title: 'Portable Digital Luggage Scale',
    description: 'Never pay overweight baggage fees again. Shows weight in kg and lbs instantly.',
    category: 'fitness',
    categoryLabel: '💪 Fitness & Health',
    priceRange: '$10 – $25',
    rating: 4.7,
    reviewCount: '22,000+',
    badge: 'Travel Essential',
    emoji: '🧳',
    features: ['Reads kg and lbs', 'Up to 50kg / 110lbs', 'Compact and portable', 'Battery included'],
    amazonUrl: `${BASE}/s?k=portable+luggage+scale&tag=${TAG}`,
    asin: 'luggage-scale',
  },
  {
    id: 'tape-measure-001',
    title: 'Professional Tape Measure (Metric/Imperial)',
    description: 'Dual-sided tape with both metric and imperial measurements. Essential for home projects.',
    category: 'tools',
    categoryLabel: '🔧 Tools & Measurement',
    priceRange: '$12 – $30',
    rating: 4.7,
    reviewCount: '14,000+',
    badge: 'DIY Essential',
    emoji: '📏',
    features: ['Metric and imperial', '25 ft / 8m length', 'Magnetic hook', 'Belt clip included'],
    amazonUrl: `${BASE}/s?k=tape+measure+metric+imperial&tag=${TAG}`,
    asin: 'tape-measure',
  },
  {
    id: 'laser-measure-001',
    title: 'Laser Distance Measurer',
    description: 'Measure rooms in meters or feet with laser precision. Perfect for renovations.',
    category: 'tools',
    categoryLabel: '🔧 Tools & Measurement',
    priceRange: '$30 – $80',
    rating: 4.6,
    reviewCount: '6,500+',
    emoji: '🔦',
    features: ['Meters and feet modes', 'Up to 40m range', 'Area and volume calc', 'Digital display'],
    amazonUrl: `${BASE}/s?k=laser+distance+measurer&tag=${TAG}`,
    asin: 'laser-measure',
  },
  {
    id: 'weather-station-001',
    title: 'Indoor Outdoor Weather Station',
    description: 'Monitor temperature in Celsius and Fahrenheit, humidity, and weather forecast.',
    category: 'tools',
    categoryLabel: '🔧 Tools & Measurement',
    priceRange: '$25 – $70',
    rating: 4.5,
    reviewCount: '7,800+',
    emoji: '🌤️',
    features: ['Celsius and Fahrenheit', 'Indoor and outdoor sensors', 'Humidity display', '3-day forecast'],
    amazonUrl: `${BASE}/s?k=indoor+outdoor+weather+station&tag=${TAG}`,
    asin: 'weather-station',
  },
  {
    id: 'travel-adapter-001',
    title: 'Universal Travel Adapter',
    description: 'Works in 150+ countries. USB-C, USB-A ports included. Essential for international travel.',
    category: 'travel',
    categoryLabel: '✈️ Travel',
    priceRange: '$20 – $50',
    rating: 4.7,
    reviewCount: '31,000+',
    badge: 'Travel Must-Have',
    emoji: '🔌',
    features: ['Works in 150+ countries', 'USB-C and USB-A ports', 'Compact design', 'Safety certified'],
    amazonUrl: `${BASE}/s?k=universal+travel+adapter&tag=${TAG}`,
    asin: 'travel-adapter',
  },
  {
    id: 'rfid-wallet-001',
    title: 'RFID Blocking Travel Wallet',
    description: 'Keep cards and cash secure while traveling internationally. Slim and lightweight.',
    category: 'travel',
    categoryLabel: '✈️ Travel',
    priceRange: '$15 – $40',
    rating: 4.6,
    reviewCount: '12,500+',
    emoji: '👜',
    features: ['RFID blocking', 'Multiple card slots', 'Passport holder', 'Slim design'],
    amazonUrl: `${BASE}/s?k=RFID+blocking+travel+wallet&tag=${TAG}`,
    asin: 'rfid-wallet',
  },
  {
    id: 'usb-drive-001',
    title: 'SanDisk 128GB USB Flash Drive',
    description: 'Fast and reliable storage for photos, documents and backups.',
    category: 'tech',
    categoryLabel: '💻 Tech & Digital',
    priceRange: '$15 – $30',
    rating: 4.7,
    reviewCount: '45,000+',
    badge: 'Best Value',
    emoji: '💾',
    features: ['128GB storage', 'USB 3.0 speed', 'Compact design', '5-year warranty'],
    amazonUrl: `${BASE}/s?k=SanDisk+128GB+USB+flash+drive&tag=${TAG}`,
    asin: 'usb-drive',
  },
  {
    id: 'external-hdd-001',
    title: 'Portable External Hard Drive 1TB',
    description: 'Back up all your photos, videos and documents. Plug and play, no setup required.',
    category: 'tech',
    categoryLabel: '💻 Tech & Digital',
    priceRange: '$55 – $90',
    rating: 4.6,
    reviewCount: '28,000+',
    emoji: '🖥️',
    features: ['1TB storage', 'USB 3.0', 'No power adapter needed', 'Compatible with PC and Mac'],
    amazonUrl: `${BASE}/s?k=portable+external+hard+drive+1TB&tag=${TAG}`,
    asin: 'external-hdd',
  },
];

export const SHOP_CATEGORIES = [
  { id: 'all', label: '🛍️ All Products' },
  { id: 'cooking', label: '🍳 Kitchen & Cooking' },
  { id: 'fitness', label: '💪 Fitness & Health' },
  { id: 'tools', label: '🔧 Tools & Measurement' },
  { id: 'travel', label: '✈️ Travel' },
  { id: 'tech', label: '💻 Tech & Digital' },
];

export function getProductsByCategory(category: string): ShopProduct[] {
  if (category === 'all') return SHOP_PRODUCTS;
  return SHOP_PRODUCTS.filter(p => p.category === category);
}
