export interface ShopProduct {
  id: string;
  title: string;
  description: string;
  category: string;
  categoryLabel: string;
  priceRange: string;
  rating: number;
  reviewCount: string;
  badge?: string;
  emoji: string;
  commission: string;
  features: string[];
  amazonUrl: string;
  globalDemand: string;
}

const TAG = 'convertnow-20';
const BASE = 'https://www.amazon.ca';

export const SHOP_PRODUCTS: ShopProduct[] = [
  // LUXURY BEAUTY — 10% Commission
  {
    id: 'lb-001',
    title: 'TruSkin Vitamin C Serum',
    description: 'Best-selling anti-aging serum. Brightens skin, reduces dark spots and fine lines.',
    category: 'luxury-beauty',
    categoryLabel: '💄 Luxury Beauty',
    priceRange: '$25 – $40',
    rating: 4.4,
    reviewCount: '98,000+',
    badge: '#1 Best Seller',
    emoji: '✨',
    commission: '10%',
    features: ['Anti-aging formula','Reduces dark spots','Brightening effect','All skin types'],
    amazonUrl: `${BASE}/s?k=TruSkin+Vitamin+C+Serum&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'lb-002',
    title: 'Olay Regenerist Micro-Sculpting Cream',
    description: 'Award-winning anti-aging moisturizer with hyaluronic acid.',
    category: 'luxury-beauty',
    categoryLabel: '💄 Luxury Beauty',
    priceRange: '$30 – $55',
    rating: 4.6,
    reviewCount: '45,000+',
    badge: 'Award Winner',
    emoji: '🏆',
    commission: '10%',
    features: ['Hyaluronic acid','Firms skin','Anti-aging','Fragrance-free'],
    amazonUrl: `${BASE}/s?k=Olay+Regenerist+Micro-Sculpting+Cream&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'lb-003',
    title: 'Neutrogena Hydro Boost Water Gel',
    description: 'Hyaluronic acid moisturizer that delivers 72-hour hydration.',
    category: 'luxury-beauty',
    categoryLabel: '💄 Luxury Beauty',
    priceRange: '$20 – $35',
    rating: 4.5,
    reviewCount: '52,000+',
    badge: 'Dermatologist Tested',
    emoji: '💧',
    commission: '10%',
    features: ['72hr hydration','Oil-free','Non-comedogenic','Fast absorbing'],
    amazonUrl: `${BASE}/s?k=Neutrogena+Hydro+Boost+Water+Gel&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'lb-004',
    title: 'CeraVe Moisturizing Cream 19oz',
    description: 'Dermatologist recommended moisturizer with ceramides and hyaluronic acid.',
    category: 'luxury-beauty',
    categoryLabel: '💄 Luxury Beauty',
    priceRange: '$18 – $30',
    rating: 4.8,
    reviewCount: '120,000+',
    badge: 'Dermatologist #1 Pick',
    emoji: '🔬',
    commission: '10%',
    features: ['3 essential ceramides','Hyaluronic acid','Fragrance-free','Face and body'],
    amazonUrl: `${BASE}/s?k=CeraVe+Moisturizing+Cream+19oz&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'lb-005',
    title: 'The Ordinary Niacinamide 10% + Zinc 1%',
    description: 'High-strength serum that reduces the appearance of blemishes and pores.',
    category: 'luxury-beauty',
    categoryLabel: '💄 Luxury Beauty',
    priceRange: '$10 – $18',
    rating: 4.4,
    reviewCount: '85,000+',
    badge: 'Viral TikTok Product',
    emoji: '🧪',
    commission: '10%',
    features: ['10% niacinamide','Reduces pores','Controls oil','Vegan formula'],
    amazonUrl: `${BASE}/s?k=The+Ordinary+Niacinamide+10+Zinc&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'lb-006',
    title: 'Dyson Airwrap Multi-Styler',
    description: 'Style, dry and finish hair with no extreme heat.',
    category: 'luxury-beauty',
    categoryLabel: '💄 Luxury Beauty',
    priceRange: '$500 – $600',
    rating: 4.4,
    reviewCount: '22,000+',
    badge: 'Viral Product',
    emoji: '💫',
    commission: '10%',
    features: ['No extreme heat','Multiple attachments','Coanda effect','Long-lasting style'],
    amazonUrl: `${BASE}/s?k=Dyson+Airwrap+Multi-Styler&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'lb-007',
    title: 'Maybelline Sky High Mascara',
    description: 'Buildable, lengthening mascara that goes sky high.',
    category: 'luxury-beauty',
    categoryLabel: '💄 Luxury Beauty',
    priceRange: '$10 – $16',
    rating: 4.5,
    reviewCount: '78,000+',
    badge: 'TikTok Viral',
    emoji: '🎭',
    commission: '10%',
    features: ['Buildable formula','Volumizing','Lengthening','Easy to remove'],
    amazonUrl: `${BASE}/s?k=Maybelline+Sky+High+Mascara&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'lb-008',
    title: 'Revlon One-Step Hair Dryer and Volumizer',
    description: 'Iconic 2-in-1 dryer and volumizer brush.',
    category: 'luxury-beauty',
    categoryLabel: '💄 Luxury Beauty',
    priceRange: '$40 – $65',
    rating: 4.4,
    reviewCount: '92,000+',
    badge: 'Amazon Choice',
    emoji: '💨',
    commission: '10%',
    features: ['2-in-1 dryer + volumizer','Reduces frizz','Adds shine','Oval brush design'],
    amazonUrl: `${BASE}/s?k=Revlon+One-Step+Hair+Dryer+Volumizer&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'lb-009',
    title: 'Laneige Lip Sleeping Mask',
    description: 'Cult Korean beauty overnight lip mask.',
    category: 'luxury-beauty',
    categoryLabel: '💄 Luxury Beauty',
    priceRange: '$22 – $30',
    rating: 4.6,
    reviewCount: '48,000+',
    badge: 'K-Beauty Bestseller',
    emoji: '🌙',
    commission: '10%',
    features: ['Overnight treatment','Berry mix scent','Vitamin C','20g jar'],
    amazonUrl: `${BASE}/s?k=Laneige+Lip+Sleeping+Mask&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'lb-010',
    title: 'Mighty Patch Original Acne Patches',
    description: 'Viral hydrocolloid patches that absorb pimple gunk overnight.',
    category: 'luxury-beauty',
    categoryLabel: '💄 Luxury Beauty',
    priceRange: '$13 – $20',
    rating: 4.5,
    reviewCount: '140,000+',
    badge: 'Viral Bestseller',
    emoji: '⭐',
    commission: '10%',
    features: ['Hydrocolloid technology','Works overnight','36 patches','Drug-free'],
    amazonUrl: `${BASE}/s?k=Mighty+Patch+Original+acne+patches&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  // KITCHEN & HOME — 4.5% Commission
  {
    id: 'kh-001',
    title: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker',
    description: 'The #1 best-selling kitchen appliance on Amazon.',
    category: 'kitchen',
    categoryLabel: '🍳 Kitchen & Home',
    priceRange: '$80 – $130',
    rating: 4.7,
    reviewCount: '180,000+',
    badge: '#1 Kitchen Bestseller',
    emoji: '🫕',
    commission: '4.5%',
    features: ['7-in-1 functions','6 quart','13 smart programs','UL certified'],
    amazonUrl: `${BASE}/s?k=Instant+Pot+Duo+7+in+1+6+quart&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'kh-002',
    title: 'Ninja Air Fryer Pro 5.5 Quart',
    description: 'Air fry, roast, reheat and dehydrate with 85% less fat.',
    category: 'kitchen',
    categoryLabel: '🍳 Kitchen & Home',
    priceRange: '$80 – $130',
    rating: 4.7,
    reviewCount: '65,000+',
    badge: 'Trending 2025',
    emoji: '🍟',
    commission: '4.5%',
    features: ['85% less fat','5.5 QT','4-in-1 functions','Dishwasher safe'],
    amazonUrl: `${BASE}/s?k=Ninja+Air+Fryer+Pro+5+quart&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'kh-003',
    title: 'Stanley Quencher Tumbler 40oz',
    description: 'The iconic tumbler that keeps drinks cold all day.',
    category: 'kitchen',
    categoryLabel: '🍳 Kitchen & Home',
    priceRange: '$35 – $55',
    rating: 4.7,
    reviewCount: '95,000+',
    badge: 'Viral Sensation',
    emoji: '🥤',
    commission: '4.5%',
    features: ['Cold 2 days','Hot 7hrs','Fits cup holders','Dishwasher safe'],
    amazonUrl: `${BASE}/s?k=Stanley+Quencher+40oz+tumbler&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'kh-004',
    title: 'Vitamix 5200 Professional Blender',
    description: 'Professional-grade blender used by chefs worldwide.',
    category: 'kitchen',
    categoryLabel: '🍳 Kitchen & Home',
    priceRange: '$350 – $450',
    rating: 4.8,
    reviewCount: '28,000+',
    badge: 'Professional Grade',
    emoji: '🌀',
    commission: '4.5%',
    features: ['Aircraft-grade steel blades','Variable speed','Self-cleaning','10-year warranty'],
    amazonUrl: `${BASE}/s?k=Vitamix+5200+blender&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'kh-005',
    title: 'KitchenAid Stand Mixer 5 Quart Artisan',
    description: 'Iconic stand mixer with 10 speeds.',
    category: 'kitchen',
    categoryLabel: '🍳 Kitchen & Home',
    priceRange: '$350 – $500',
    rating: 4.8,
    reviewCount: '42,000+',
    badge: 'Iconic Appliance',
    emoji: '🎂',
    commission: '4.5%',
    features: ['10 speeds','5 quart bowl','59 touch-points','20+ attachments'],
    amazonUrl: `${BASE}/s?k=KitchenAid+Artisan+stand+mixer+5+quart&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'kh-006',
    title: 'Nespresso Vertuo Coffee Machine',
    description: 'One-touch coffee in 4 sizes.',
    category: 'kitchen',
    categoryLabel: '🍳 Kitchen & Home',
    priceRange: '$150 – $250',
    rating: 4.6,
    reviewCount: '35,000+',
    badge: 'Coffee Lovers Choice',
    emoji: '☕',
    commission: '4.5%',
    features: ['4 cup sizes','One-touch brew','Centrifusion tech','Energy saving'],
    amazonUrl: `${BASE}/s?k=Nespresso+Vertuo+coffee+machine&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'kh-007',
    title: 'Dyson V15 Detect Cordless Vacuum',
    description: 'Laser detects invisible dust.',
    category: 'kitchen',
    categoryLabel: '🍳 Kitchen & Home',
    priceRange: '$600 – $800',
    rating: 4.6,
    reviewCount: '12,000+',
    badge: 'Premium Pick',
    emoji: '🌀',
    commission: '4.5%',
    features: ['Laser dust detection','LCD screen','60min run time','5 year warranty'],
    amazonUrl: `${BASE}/s?k=Dyson+V15+Detect+cordless+vacuum&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'kh-008',
    title: 'iRobot Roomba Robot Vacuum',
    description: 'Self-emptying robot vacuum that maps your home.',
    category: 'kitchen',
    categoryLabel: '🍳 Kitchen & Home',
    priceRange: '$300 – $500',
    rating: 4.5,
    reviewCount: '28,000+',
    badge: 'Smart Home Essential',
    emoji: '🤖',
    commission: '4.5%',
    features: ['Self-emptying base','Smart mapping','Alexa compatible','Auto recharge'],
    amazonUrl: `${BASE}/s?k=iRobot+Roomba+robot+vacuum+self+emptying&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'kh-009',
    title: 'Le Creuset Enameled Cast Iron Dutch Oven',
    description: 'Luxury French cookware.',
    category: 'kitchen',
    categoryLabel: '🍳 Kitchen & Home',
    priceRange: '$200 – $400',
    rating: 4.8,
    reviewCount: '9,500+',
    badge: 'Luxury Cookware',
    emoji: '🫕',
    commission: '4.5%',
    features: ['Enameled cast iron','Even heat','Oven safe 500°F','Lifetime warranty'],
    amazonUrl: `${BASE}/s?k=Le+Creuset+dutch+oven+enameled+cast+iron&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'kh-010',
    title: 'Lodge Cast Iron Skillet 12 inch',
    description: 'Pre-seasoned cast iron that lasts a lifetime.',
    category: 'kitchen',
    categoryLabel: '🍳 Kitchen & Home',
    priceRange: '$35 – $65',
    rating: 4.8,
    reviewCount: '88,000+',
    badge: 'Lifetime Investment',
    emoji: '🍳',
    commission: '4.5%',
    features: ['Pre-seasoned','All stovetops','Oven safe 500°F','Made in USA'],
    amazonUrl: `${BASE}/s?k=Lodge+cast+iron+skillet+12+inch&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  // PET SUPPLIES — 3% Commission
  {
    id: 'pet-001',
    title: 'KONG Classic Dog Toy',
    description: 'The #1 vet recommended dog toy.',
    category: 'pets',
    categoryLabel: '🐾 Pet Supplies',
    priceRange: '$12 – $25',
    rating: 4.7,
    reviewCount: '125,000+',
    badge: 'Vet Recommended #1',
    emoji: '🐕',
    commission: '3%',
    features: ['Natural rubber','Stuffable with treats','Multiple sizes','Dishwasher safe'],
    amazonUrl: `${BASE}/s?k=KONG+Classic+Dog+Toy&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'pet-002',
    title: 'Furbo 360° Dog Camera with Treat Toss',
    description: 'See, talk and toss treats to your dog from anywhere.',
    category: 'pets',
    categoryLabel: '🐾 Pet Supplies',
    priceRange: '$120 – $180',
    rating: 4.4,
    reviewCount: '18,000+',
    badge: 'Smart Pet Tech',
    emoji: '📷',
    commission: '3%',
    features: ['360° camera','Treat tosser','2-way audio','Alexa compatible'],
    amazonUrl: `${BASE}/s?k=Furbo+360+dog+camera+treat+toss&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'pet-003',
    title: 'Catit Flower Fountain 3L',
    description: 'Triple-action filter water fountain for cats.',
    category: 'pets',
    categoryLabel: '🐾 Pet Supplies',
    priceRange: '$30 – $50',
    rating: 4.4,
    reviewCount: '32,000+',
    badge: 'Cat Owner Must-Have',
    emoji: '🐱',
    commission: '3%',
    features: ['3L capacity','Triple filtration','Flower fountain','Quiet pump'],
    amazonUrl: `${BASE}/s?k=Catit+Flower+Fountain+3+liter&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'pet-004',
    title: 'Furminator deShedding Tool for Dogs',
    description: 'Reduces shedding up to 90%.',
    category: 'pets',
    categoryLabel: '🐾 Pet Supplies',
    priceRange: '$25 – $55',
    rating: 4.6,
    reviewCount: '72,000+',
    badge: 'Grooming Bestseller',
    emoji: '🐶',
    commission: '3%',
    features: ['90% less shedding','Stainless steel edge','FURejector button','Multiple sizes'],
    amazonUrl: `${BASE}/s?k=FURminator+deShedding+Tool+dog&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'pet-005',
    title: 'Petlibro Automatic Pet Feeder 4L',
    description: 'Program up to 6 meals per day with portion control.',
    category: 'pets',
    categoryLabel: '🐾 Pet Supplies',
    priceRange: '$45 – $90',
    rating: 4.4,
    reviewCount: '22,000+',
    badge: 'Smart Pet Gadget',
    emoji: '🍽️',
    commission: '3%',
    features: ['6 meals per day','App control','4L capacity','Voice recording'],
    amazonUrl: `${BASE}/s?k=Petlibro+automatic+pet+feeder+wifi+app&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  // BABY PRODUCTS — 3% Commission
  {
    id: 'baby-001',
    title: 'Baby Brezza Formula Pro Advanced',
    description: 'Automatically makes a warm, formula bottle in seconds.',
    category: 'baby',
    categoryLabel: '👶 Baby & Nursery',
    priceRange: '$200 – $250',
    rating: 4.3,
    reviewCount: '12,000+',
    badge: 'New Parent Essential',
    emoji: '🍼',
    commission: '3%',
    features: ['Instant warm bottles','Auto formula dispensing','Adjustable temperature','Easy clean'],
    amazonUrl: `${BASE}/s?k=Baby+Brezza+Formula+Pro+Advanced&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'baby-002',
    title: 'Hatch Rest Baby Sound Machine',
    description: 'Sound machine, night light and time-to-rise clock.',
    category: 'baby',
    categoryLabel: '👶 Baby & Nursery',
    priceRange: '$60 – $90',
    rating: 4.7,
    reviewCount: '28,000+',
    badge: 'Sleep Essential',
    emoji: '🌙',
    commission: '3%',
    features: ['Sound machine','Night light','App controlled','Time-to-rise'],
    amazonUrl: `${BASE}/s?k=Hatch+Rest+Baby+Sound+Machine&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'baby-003',
    title: 'Ergobaby Omni 360 Baby Carrier',
    description: 'All-position baby carrier for newborns to toddlers.',
    category: 'baby',
    categoryLabel: '👶 Baby & Nursery',
    priceRange: '$150 – $200',
    rating: 4.6,
    reviewCount: '15,000+',
    badge: 'Best Carrier',
    emoji: '👶',
    commission: '3%',
    features: ['4 carry positions','Newborn to 45lbs','Lumbar support','Breathable'],
    amazonUrl: `${BASE}/s?k=Ergobaby+Omni+360+baby+carrier&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'baby-004',
    title: 'Nanit Pro Smart Baby Monitor',
    description: 'HD video baby monitor with breathing tracking.',
    category: 'baby',
    categoryLabel: '👶 Baby & Nursery',
    priceRange: '$200 – $350',
    rating: 4.5,
    reviewCount: '9,500+',
    badge: 'Tech-Forward Parents',
    emoji: '📸',
    commission: '3%',
    features: ['HD video','Breathing tracking','Sleep analysis','Two-way audio'],
    amazonUrl: `${BASE}/s?k=Nanit+Pro+Smart+Baby+Monitor&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  // BOOKS — 4.5% Commission
  {
    id: 'book-001',
    title: 'Atomic Habits by James Clear',
    description: 'The #1 most read personal development book.',
    category: 'books',
    categoryLabel: '📚 Books & Education',
    priceRange: '$18 – $28',
    rating: 4.8,
    reviewCount: '180,000+',
    badge: '#1 Bestseller',
    emoji: '⚛️',
    commission: '4.5%',
    features: ['#1 NYT Bestseller','Habit formation','Easy to read','Life changing'],
    amazonUrl: `${BASE}/s?k=Atomic+Habits+James+Clear+hardcover&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'book-002',
    title: 'Rich Dad Poor Dad by Robert Kiyosaki',
    description: 'The #1 personal finance book of all time.',
    category: 'books',
    categoryLabel: '📚 Books & Education',
    priceRange: '$12 – $18',
    rating: 4.7,
    reviewCount: '92,000+',
    badge: 'Finance Classic',
    emoji: '💰',
    commission: '4.5%',
    features: ['Personal finance','Investment mindset','Asset vs liability','25th anniversary edition'],
    amazonUrl: `${BASE}/s?k=Rich+Dad+Poor+Dad+Robert+Kiyosaki&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'book-003',
    title: 'The Psychology of Money by Morgan Housel',
    description: 'Timeless lessons on wealth, greed and happiness.',
    category: 'books',
    categoryLabel: '📚 Books & Education',
    priceRange: '$15 – $22',
    rating: 4.7,
    reviewCount: '55,000+',
    badge: 'Must Read 2025',
    emoji: '🧠',
    commission: '4.5%',
    features: ['19 money lessons','Easy to read','International bestseller','Gift worthy'],
    amazonUrl: `${BASE}/s?k=The+Psychology+of+Money+Morgan+Housel&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'book-004',
    title: 'The 48 Laws of Power by Robert Greene',
    description: 'The amoral, ruthless laws of power from 3,000 years of history.',
    category: 'books',
    categoryLabel: '📚 Books & Education',
    priceRange: '$18 – $28',
    rating: 4.7,
    reviewCount: '38,000+',
    badge: 'Power Classic',
    emoji: '♟️',
    commission: '4.5%',
    features: ['48 laws explained','Historical examples','Illustrated edition','Hardcover available'],
    amazonUrl: `${BASE}/s?k=The+48+Laws+of+Power+Robert+Greene&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  {
    id: 'book-005',
    title: "Can't Hurt Me by David Goggins",
    description: 'From poverty and abuse to SEAL team member.',
    category: 'books',
    categoryLabel: '📚 Books & Education',
    priceRange: '$18 – $28',
    rating: 4.8,
    reviewCount: '75,000+',
    badge: 'Motivational #1',
    emoji: '💪',
    commission: '4.5%',
    features: ['Motivational memoir','Mental toughness','Navy SEAL','Raw and honest'],
    amazonUrl: `${BASE}/s?k=Cant+Hurt+Me+David+Goggins&tag=${TAG}`,
    globalDemand: '🌍 USA · CA · UK · AU',
  },
  // FITNESS & HEALTH — 3% Commission
  { id: 'fit-001', title: 'Fitbit Charge 6 Fitness Tracker', description: 'Advanced fitness tracker with heart rate, GPS, sleep tracking.', category: 'fitness', categoryLabel: '💪 Fitness & Health', priceRange: '$150 – $180', rating: 4.4, reviewCount: '28,000+', badge: 'Best Fitness Tracker', emoji: '⌚', commission: '3%', features: ['Built-in GPS','Heart rate','Sleep tracking','Google Wallet'], amazonUrl: `${BASE}/s?k=Fitbit+Charge+6+fitness+tracker&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'fit-002', title: 'Theragun Prime Percussive Massage', description: 'Professional-grade percussion therapy device.', category: 'fitness', categoryLabel: '💪 Fitness & Health', priceRange: '$200 – $300', rating: 4.6, reviewCount: '15,000+', badge: 'Pro Recovery Tool', emoji: '💆', commission: '3%', features: ['5 attachments','2 hours battery','Quiet force tech','App guided routines'], amazonUrl: `${BASE}/s?k=Theragun+Prime+percussive+massager&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'fit-003', title: 'Lululemon Everywhere Belt Bag', description: 'The viral belt bag that goes everywhere.', category: 'fitness', categoryLabel: '💪 Fitness & Health', priceRange: '$38 – $48', rating: 4.7, reviewCount: '22,000+', badge: 'TikTok Viral', emoji: '👜', commission: '3%', features: ['Water repellent','Multiple colors','Hands-free','Spacious interior'], amazonUrl: `${BASE}/s?k=Lululemon+Everywhere+Belt+Bag&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'fit-004', title: 'Manduka PRO Yoga Mat 6mm', description: 'Professional yoga mat used in studios worldwide.', category: 'fitness', categoryLabel: '💪 Fitness & Health', priceRange: '$88 – $120', rating: 4.6, reviewCount: '18,000+', badge: 'Studio Quality', emoji: '🧘', commission: '3%', features: ['6mm thick','Lifetime guarantee','Closed cell surface','Eco-certified'], amazonUrl: `${BASE}/s?k=Manduka+PRO+yoga+mat+6mm&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'fit-005', title: 'Optimum Nutrition Gold Standard Whey Protein', description: 'World\'s best-selling whey protein.', category: 'fitness', categoryLabel: '💪 Fitness & Health', priceRange: '$40 – $80', rating: 4.6, reviewCount: '85,000+', badge: '#1 Protein Worldwide', emoji: '🥛', commission: '3%', features: ['24g protein','5.5g BCAAs','100+ flavors','Subscribe and save'], amazonUrl: `${BASE}/s?k=Optimum+Nutrition+Gold+Standard+Whey+Protein&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'fit-006', title: 'Hydro Flask 32oz Wide Mouth', description: 'Insulated water bottle keeps drinks cold 24hrs.', category: 'fitness', categoryLabel: '💪 Fitness & Health', priceRange: '$40 – $55', rating: 4.8, reviewCount: '52,000+', badge: 'Cult Favourite', emoji: '💧', commission: '3%', features: ['Cold 24hrs','Hot 12hrs','Wide mouth','Lifetime warranty'], amazonUrl: `${BASE}/s?k=Hydro+Flask+32oz+Wide+Mouth+water+bottle&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  // TECH & GADGETS — 3% Commission
  { id: 'tech-001', title: 'Apple AirPods Pro 2nd Generation', description: 'Active noise cancellation, Adaptive Transparency.', category: 'tech', categoryLabel: '💻 Tech & Gadgets', priceRange: '$280 – $330', rating: 4.6, reviewCount: '45,000+', badge: 'Apple Bestseller', emoji: '🎧', commission: '3%', features: ['Active noise cancellation','Adaptive transparency','Spatial audio','MagSafe case'], amazonUrl: `${BASE}/s?k=Apple+AirPods+Pro+2nd+generation&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'tech-002', title: 'Anker 65W USB-C Charging Station', description: 'Charge laptop, phone and tablet simultaneously.', category: 'tech', categoryLabel: '💻 Tech & Gadgets', priceRange: '$25 – $50', rating: 4.7, reviewCount: '38,000+', badge: 'WFH Essential', emoji: '⚡', commission: '3%', features: ['65W total power','3 ports','GaN technology','Foldable plug'], amazonUrl: `${BASE}/s?k=Anker+65W+USB-C+charging+station&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'tech-003', title: 'Samsung 65-inch 4K QLED Smart TV', description: '4K QLED TV with Quantum Dot technology.', category: 'tech', categoryLabel: '💻 Tech & Gadgets', priceRange: '$700 – $1,200', rating: 4.6, reviewCount: '18,000+', badge: 'High Ticket Item', emoji: '📺', commission: '3%', features: ['4K QLED','Quantum Dot','Built-in Alexa','Gaming mode'], amazonUrl: `${BASE}/s?k=Samsung+65+inch+QLED+4K+Smart+TV&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'tech-004', title: 'iPad 10th Generation', description: 'Powerful and versatile tablet with USB-C.', category: 'tech', categoryLabel: '💻 Tech & Gadgets', priceRange: '$350 – $500', rating: 4.7, reviewCount: '22,000+', badge: 'Top Tablet Pick', emoji: '📱', commission: '3%', features: ['A14 Bionic chip','USB-C','10.9 inch display','All-day battery'], amazonUrl: `${BASE}/s?k=iPad+10th+generation&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'tech-005', title: 'Logitech MX Master 3S Mouse', description: 'Advanced wireless mouse for professionals.', category: 'tech', categoryLabel: '💻 Tech & Gadgets', priceRange: '$90 – $120', rating: 4.7, reviewCount: '28,000+', badge: 'WFH Favourite', emoji: '🖱️', commission: '3%', features: ['Ultra-fast scroll','Silent clicks','Multi-device','Ergonomic design'], amazonUrl: `${BASE}/s?k=Logitech+MX+Master+3S+wireless+mouse&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'tech-006', title: 'Ring Video Doorbell Pro 2', description: 'Smart video doorbell with 3D motion detection.', category: 'tech', categoryLabel: '💻 Tech & Gadgets', priceRange: '$200 – $280', rating: 4.5, reviewCount: '14,000+', badge: 'Smart Home Essential', emoji: '🔔', commission: '3%', features: ['Head-to-toe HD','3D motion detection','Two-way talk','Alexa compatible'], amazonUrl: `${BASE}/s?k=Ring+Video+Doorbell+Pro+2&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'tech-007', title: 'Amazon Echo Dot 5th Generation', description: 'Smart speaker with Alexa.', category: 'tech', categoryLabel: '💻 Tech & Gadgets', priceRange: '$50 – $70', rating: 4.6, reviewCount: '65,000+', badge: 'Smart Home Starter', emoji: '🔊', commission: '3%', features: ['Improved sound','Alexa built-in','Motion sensor','Temperature sensor'], amazonUrl: `${BASE}/s?k=Amazon+Echo+Dot+5th+generation&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'tech-008', title: 'WD 4TB My Passport Portable Hard Drive', description: 'Ultra-compact 4TB portable storage.', category: 'tech', categoryLabel: '💻 Tech & Gadgets', priceRange: '$100 – $140', rating: 4.6, reviewCount: '32,000+', badge: 'Best Storage Value', emoji: '💾', commission: '3%', features: ['4TB capacity','USB 3.0','Password protection','Compact design'], amazonUrl: `${BASE}/s?k=WD+4TB+My+Passport+portable+hard+drive&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  // HOME IMPROVEMENT — 3% Commission
  { id: 'home-001', title: 'LEVOIT Air Purifier for Large Room', description: 'HEPA air purifier for rooms up to 1095 sq ft.', category: 'home', categoryLabel: '🏠 Home Improvement', priceRange: '$100 – $180', rating: 4.6, reviewCount: '28,000+', badge: 'Air Quality Essential', emoji: '🌬️', commission: '3%', features: ['HEPA filter','1095 sq ft coverage','Sleep mode','Air quality indicator'], amazonUrl: `${BASE}/s?k=LEVOIT+Air+Purifier+large+room+HEPA&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'home-002', title: 'Nest Learning Thermostat 3rd Gen', description: 'Smart thermostat that learns your schedule.', category: 'home', categoryLabel: '🏠 Home Improvement', priceRange: '$200 – $280', rating: 4.6, reviewCount: '22,000+', badge: 'Energy Saver', emoji: '🌡️', commission: '3%', features: ['Self-learning','Energy savings','Remote control','Works with Alexa'], amazonUrl: `${BASE}/s?k=Nest+Learning+Thermostat+3rd+generation&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'home-003', title: 'Govee Smart LED Strip Lights 16.4ft', description: 'App and voice controlled RGB LED strip.', category: 'home', categoryLabel: '🏠 Home Improvement', priceRange: '$20 – $40', rating: 4.4, reviewCount: '52,000+', badge: 'Room Makeover Fave', emoji: '💡', commission: '3%', features: ['App controlled','Music sync','16 million colors','Alexa and Google Home'], amazonUrl: `${BASE}/s?k=Govee+Smart+LED+Strip+Lights+16.4ft&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'home-004', title: 'BLACK+DECKER 20V Cordless Drill', description: 'Compact and lightweight drill driver.', category: 'home', categoryLabel: '🏠 Home Improvement', priceRange: '$50 – $80', rating: 4.6, reviewCount: '42,000+', badge: 'DIY Bestseller', emoji: '🔧', commission: '3%', features: ['20V battery','11-position clutch','LED work light','Compact 7.7 inch'], amazonUrl: `${BASE}/s?k=BLACK+DECKER+20V+cordless+drill+driver&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  // FASHION & APPAREL — 4% Commission
  { id: 'fashion-001', title: 'Carhartt Beanie Hat Original Fit', description: 'Iconic ribbed knit beanie.', category: 'fashion', categoryLabel: '👗 Fashion & Apparel', priceRange: '$18 – $28', rating: 4.8, reviewCount: '78,000+', badge: 'Winter Essential', emoji: '🧢', commission: '4%', features: ['Stretchable fit','Acrylic knit','30+ colors','One size fits most'], amazonUrl: `${BASE}/s?k=Carhartt+beanie+hat+original+fit&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'fashion-002', title: 'Columbia Sportswear Arcadia Rain Jacket', description: 'Waterproof, packable rain jacket.', category: 'fashion', categoryLabel: '👗 Fashion & Apparel', priceRange: '$60 – $110', rating: 4.5, reviewCount: '32,000+', badge: 'Outdoor Essential', emoji: '🧥', commission: '4%', features: ['Waterproof','Packable','Adjustable hood','Omni-Tech sealed seams'], amazonUrl: `${BASE}/s?k=Columbia+Arcadia+rain+jacket+women&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'fashion-003', title: 'Nike Dri-FIT Training T-Shirt', description: 'Moisture-wicking athletic shirt.', category: 'fashion', categoryLabel: '👗 Fashion & Apparel', priceRange: '$25 – $45', rating: 4.5, reviewCount: '22,000+', badge: 'Gym Staple', emoji: '👕', commission: '4%', features: ['Dri-FIT technology','Moisture-wicking','Lightweight','Multiple colors'], amazonUrl: `${BASE}/s?k=Nike+Dri-FIT+training+t-shirt&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'fashion-004', title: 'Herschel Little America Backpack', description: 'Iconic backpack with laptop sleeve.', category: 'fashion', categoryLabel: '👗 Fashion & Apparel', priceRange: '$70 – $100', rating: 4.6, reviewCount: '25,000+', badge: 'Style Icon', emoji: '🎒', commission: '4%', features: ['25L capacity','Laptop sleeve','Padded straps','50+ colorways'], amazonUrl: `${BASE}/s?k=Herschel+Little+America+backpack&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  // TRAVEL — 4% Commission
  { id: 'travel-001', title: 'Samsonite Winfield 3 Hardside Spinner Luggage', description: 'Lightweight hardside suitcase with 360° spinner wheels.', category: 'travel', categoryLabel: '✈️ Travel & Outdoors', priceRange: '$100 – $250', rating: 4.6, reviewCount: '28,000+', badge: 'Traveler Favourite', emoji: '🧳', commission: '4%', features: ['Lightweight','TSA lock','360° spinner wheels','10-year warranty'], amazonUrl: `${BASE}/s?k=Samsonite+Winfield+3+hardside+spinner+luggage&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'travel-002', title: 'Bose QuietComfort 45 Noise Cancelling Headphones', description: 'World-class noise cancelling headphones.', category: 'travel', categoryLabel: '✈️ Travel & Outdoors', priceRange: '$250 – $330', rating: 4.6, reviewCount: '22,000+', badge: 'Flight Essential', emoji: '🎧', commission: '4%', features: ['World-class ANC','24hr battery','Foldable','Bluetooth 5.1'], amazonUrl: `${BASE}/s?k=Bose+QuietComfort+45+headphones&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'travel-003', title: 'Compression Packing Cubes 8-Piece Set', description: 'Compress clothes down to save space.', category: 'travel', categoryLabel: '✈️ Travel & Outdoors', priceRange: '$25 – $45', rating: 4.7, reviewCount: '35,000+', badge: 'Packing Hack', emoji: '📦', commission: '4%', features: ['Compresses 60%','8-piece set','Lightweight nylon','Multiple colors'], amazonUrl: `${BASE}/s?k=compression+packing+cubes+8+piece+set&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'travel-004', title: 'Portable Power Bank 26800mAh', description: 'Charge phone 6+ times. Airline approved.', category: 'travel', categoryLabel: '✈️ Travel & Outdoors', priceRange: '$35 – $60', rating: 4.6, reviewCount: '32,000+', badge: 'Travel Must-Have', emoji: '🔋', commission: '4%', features: ['26800mAh','Charges 6+ times','USB-C + USB-A','Airline approved'], amazonUrl: `${BASE}/s?k=portable+power+bank+26800mAh+USB-C&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  // GAMING — 3% Commission
  { id: 'gaming-001', title: 'PlayStation 5 DualSense Controller', description: 'Next-gen PS5 controller with haptic feedback.', category: 'gaming', categoryLabel: '🎮 Gaming', priceRange: '$80 – $100', rating: 4.7, reviewCount: '38,000+', badge: 'Gaming Essential', emoji: '🎮', commission: '3%', features: ['Haptic feedback','Adaptive triggers','USB-C charging','Built-in microphone'], amazonUrl: `${BASE}/s?k=PlayStation+5+DualSense+controller&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'gaming-002', title: 'Nintendo Switch OLED Model', description: 'Enhanced Nintendo Switch with vivid 7-inch OLED screen.', category: 'gaming', categoryLabel: '🎮 Gaming', priceRange: '$350 – $400', rating: 4.8, reviewCount: '28,000+', badge: 'Family Favourite', emoji: '🕹️', commission: '3%', features: ['7-inch OLED','Wide stand','64GB storage','Enhanced audio'], amazonUrl: `${BASE}/s?k=Nintendo+Switch+OLED+model&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'gaming-003', title: 'Razer DeathAdder V3 Gaming Mouse', description: 'Ultra-lightweight gaming mouse with Focus Pro 30K sensor.', category: 'gaming', categoryLabel: '🎮 Gaming', priceRange: '$80 – $100', rating: 4.6, reviewCount: '14,000+', badge: 'Esports Pick', emoji: '🖱️', commission: '3%', features: ['30K DPI sensor','Ultra-lightweight','90hr battery','Razer Chroma RGB'], amazonUrl: `${BASE}/s?k=Razer+DeathAdder+V3+gaming+mouse&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  // HEALTH & WELLNESS — 3% Commission
  { id: 'wellness-001', title: 'Garden of Life Vitamin D3 5000 IU', description: 'Whole food vitamin D3 with organic olive oil.', category: 'wellness', categoryLabel: '🌿 Health & Wellness', priceRange: '$20 – $35', rating: 4.6, reviewCount: '22,000+', badge: 'Immune Support', emoji: '☀️', commission: '3%', features: ['5000 IU D3','Whole food','Organic olive oil','Non-GMO verified'], amazonUrl: `${BASE}/s?k=Garden+of+Life+Vitamin+D3+5000+IU&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'wellness-002', title: 'Nordic Naturals Omega-3 Fish Oil', description: 'The #1 fish oil brand in the US.', category: 'wellness', categoryLabel: '🌿 Health & Wellness', priceRange: '$25 – $45', rating: 4.7, reviewCount: '38,000+', badge: '#1 Fish Oil Brand', emoji: '🐟', commission: '3%', features: ['Triglyceride form','No fishy aftertaste','Third-party tested','1280mg EPA+DHA'], amazonUrl: `${BASE}/s?k=Nordic+Naturals+Ultimate+Omega+fish+oil&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'wellness-003', title: 'Magnesium Glycinate 400mg', description: 'Highly bioavailable magnesium for sleep and stress relief.', category: 'wellness', categoryLabel: '🌿 Health & Wellness', priceRange: '$18 – $30', rating: 4.6, reviewCount: '32,000+', badge: 'Sleep Aid Favourite', emoji: '😴', commission: '3%', features: ['400mg per serving','Glycinate form','Easy on stomach','No laxative effect'], amazonUrl: `${BASE}/s?k=Magnesium+Glycinate+400mg+supplement&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'wellness-004', title: 'Athletic Greens AG1 Daily Supplement', description: '75 vitamins, minerals and whole food ingredients.', category: 'wellness', categoryLabel: '🌿 Health & Wellness', priceRange: '$80 – $110', rating: 4.5, reviewCount: '12,000+', badge: 'Influencer Favourite', emoji: '🥗', commission: '3%', features: ['75 nutrients','NSF certified','Probiotic blend','Travel packets available'], amazonUrl: `${BASE}/s?k=Athletic+Greens+AG1+daily+supplement&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  // OFFICE & WFH — 4% Commission
  { id: 'office-001', title: 'Flexispot Standing Desk Electric', description: 'Electric sit-stand desk with memory settings.', category: 'office', categoryLabel: '🎒 Office & WFH', priceRange: '$250 – $450', rating: 4.5, reviewCount: '22,000+', badge: 'WFH Game Changer', emoji: '🖥️', commission: '4%', features: ['Electric height adjustment','4 memory presets','Anti-collision','3-year warranty'], amazonUrl: `${BASE}/s?k=Flexispot+electric+standing+desk+adjustable&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'office-002', title: 'Autonomous ErgoChair Pro', description: 'Ergonomic office chair with lumbar support.', category: 'office', categoryLabel: '🎒 Office & WFH', priceRange: '$300 – $500', rating: 4.4, reviewCount: '8,500+', badge: 'Back Pain Saviour', emoji: '💺', commission: '4%', features: ['Lumbar support','Adjustable armrests','Mesh back','2-year warranty'], amazonUrl: `${BASE}/s?k=ergonomic+office+chair+lumbar+support+adjustable&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'office-003', title: 'LG 27-inch 4K UHD Monitor', description: 'USB-C 4K monitor with 95% DCI-P3 color.', category: 'office', categoryLabel: '🎒 Office & WFH', priceRange: '$300 – $500', rating: 4.6, reviewCount: '15,000+', badge: 'Creator Favourite', emoji: '🖥️', commission: '4%', features: ['4K UHD','USB-C power delivery','95% DCI-P3','HDR10'], amazonUrl: `${BASE}/s?k=LG+27+inch+4K+UHD+USB-C+monitor&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'office-004', title: 'Elgato Stream Deck MK.2', description: '15 customizable LCD keys for streaming and shortcuts.', category: 'office', categoryLabel: '🎒 Office & WFH', priceRange: '$130 – $180', rating: 4.7, reviewCount: '18,000+', badge: 'Creator Essential', emoji: '🎬', commission: '4%', features: ['15 LCD keys','Fully customizable','Plugins for all apps','Detachable cable'], amazonUrl: `${BASE}/s?k=Elgato+Stream+Deck+MK2&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  // TOOLS & MEASUREMENT — 3% Commission
  { id: 'tools-001', title: 'Stanley Tape Measure 25ft FatMax', description: 'Professional grade 25ft tape measure.', category: 'tools', categoryLabel: '🔧 Tools & Measurement', priceRange: '$18 – $35', rating: 4.7, reviewCount: '38,000+', badge: 'Professional Grade', emoji: '📏', commission: '3%', features: ['25ft length','Metric and imperial','Power lock','Mylar coated blade'], amazonUrl: `${BASE}/s?k=Stanley+FatMax+25ft+tape+measure&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'tools-002', title: 'Bosch GLM 50-27 CG Laser Distance Measure', description: 'Measure distances up to 165ft with ±1/16 inch accuracy.', category: 'tools', categoryLabel: '🔧 Tools & Measurement', priceRange: '$65 – $100', rating: 4.5, reviewCount: '12,000+', badge: 'Pro Accuracy', emoji: '🔦', commission: '3%', features: ['165ft range','±1/16" accuracy','Bluetooth','Area and volume calc'], amazonUrl: `${BASE}/s?k=Bosch+GLM+laser+distance+measure&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
  { id: 'tools-003', title: 'Fluke 117 Electrician\'s Digital Multimeter', description: 'Professional multimeter for electricians.', category: 'tools', categoryLabel: '🔧 Tools & Measurement', priceRange: '$150 – $220', rating: 4.8, reviewCount: '8,500+', badge: 'Electrician Choice', emoji: '⚡', commission: '3%', features: ['True RMS','Non-contact voltage','Auto-ranging','VoltAlert technology'], amazonUrl: `${BASE}/s?k=Fluke+117+electrician+digital+multimeter&tag=${TAG}`, globalDemand: '🌍 USA · CA · UK · AU' },
];

// Categories
export const SHOP_CATEGORIES = [
  { id: 'all', label: '🛍️ All Products', commission: 'Up to 10%' },
  { id: 'luxury-beauty', label: '💄 Luxury Beauty', commission: '10%' },
  { id: 'kitchen', label: '🍳 Kitchen & Home', commission: '4.5%' },
  { id: 'books', label: '📚 Books', commission: '4.5%' },
  { id: 'fashion', label: '👗 Fashion', commission: '4%' },
  { id: 'office', label: '🎒 Office & WFH', commission: '4%' },
  { id: 'travel', label: '✈️ Travel', commission: '4%' },
  { id: 'fitness', label: '💪 Fitness', commission: '3%' },
  { id: 'wellness', label: '🌿 Health & Wellness', commission: '3%' },
  { id: 'pets', label: '🐾 Pet Supplies', commission: '3%' },
  { id: 'baby', label: '👶 Baby', commission: '3%' },
  { id: 'tech', label: '💻 Tech & Gadgets', commission: '3%' },
  { id: 'gaming', label: '🎮 Gaming', commission: '3%' },
  { id: 'home', label: '🏠 Home Improvement', commission: '3%' },
  { id: 'tools', label: '🔧 Tools', commission: '3%' },
];

export function getProductsByCategory(category: string): ShopProduct[] {
  if (category === 'all') return SHOP_PRODUCTS;
  return SHOP_PRODUCTS.filter(p => p.category === category);
}

export function getProductCount(): number {
  return SHOP_PRODUCTS.length;
}

export function getFeaturedProducts(limit = 8): ShopProduct[] {
  return SHOP_PRODUCTS.filter(p => p.badge).slice(0, limit);
}
